// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsolePlay.ef.poco
{

    // AssociatedAlloc
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class AssociatedAlloc
    {
        public int AllocationId { get; set; } // AllocationId (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public int? AssociatedId { get; set; } // AssociatedId

        // Reverse navigation

        /// <summary>
        /// Child AssociatedAllocs where [AssociatedAlloc].[AssociatedId] point to this entity (FK_AssociatedAlloc_AssociatedAlloc)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AssociatedAlloc> AssociatedAllocs { get; set; } // AssociatedAlloc.FK_AssociatedAlloc_AssociatedAlloc

        // Foreign keys

        /// <summary>
        /// Parent AssociatedAlloc pointed by [AssociatedAlloc].([AssociatedId]) (FK_AssociatedAlloc_AssociatedAlloc)
        /// </summary>
        public virtual AssociatedAlloc Associated { get; set; } // FK_AssociatedAlloc_AssociatedAlloc

        public AssociatedAlloc()
        {
            AssociatedAllocs = new System.Collections.Generic.List<AssociatedAlloc>();
        }
    }

}
// </auto-generated>
